### ISSUE TITLE
Generate .library

### ISSUE THREAD

**Issue by tiagocunico** [fisothemes/TwinCAT-Dynamic-String-Kit#1]
This is more a suggestion. You could generate the .library, so it's easy to import and upgrade.

Thanks for the great work

**Comment by fisothemes** [comment]
Yh sure, I'm planning on doing some refactoring to make it line up with Beckhoff's coding guidelines. I'll see if I'll get it done by Friday or Saturday.

**Comment by fisothemes** [comment]
Done. Please see [releases](https://github.com/fisothemes/TwinCAT-Dynamic-String-Kit/releases).
